# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auths', '0003_auto_20161110_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedentemedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='media/')),
                ('estado', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Antecedentemedicos',
                'verbose_name': 'Antecedentemedico',
                'permissions': (('list_antecedentemedico', 'Can list antecedentemedico'), ('get_antecedentemedico', 'Can get antecedentemedico')),
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedadactual', models.CharField(max_length=60)),
                ('examenfisico', models.CharField(max_length=60)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('suministrar', models.BooleanField(default=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Consultas',
                'verbose_name': 'Consulta',
                'permissions': (('list_consulta', 'Can list consulta'), ('get_consulta', 'Can get consulta')),
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
                'verbose_name': 'Departamento',
                'permissions': (('list_departamento', 'Can list departamento'), ('get_departamento', 'Can get departamento')),
            },
        ),
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('HOSPITAL', 'hospital'), ('CLINICA', 'clinica'), ('OTROS', 'otros')], default='CLINICA', max_length=50)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='topico2.Consulta')),
            ],
            options={
                'verbose_name_plural': 'Derivacions',
                'verbose_name': 'Derivacion',
                'permissions': (('list_derivacion', 'Can list derivacion'), ('get_derivacion', 'Can get derivacion')),
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Diagnosticos',
                'verbose_name': 'Diagnostico',
                'permissions': (('list_diagnostico', 'Can list diagnostico'), ('get_diagnostico', 'Can get diagnostico')),
            },
        ),
        migrations.CreateModel(
            name='EspecificacionReceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('dosis', models.IntegerField()),
                ('periodo', models.CharField(max_length=20)),
                ('recomendacion', models.TextField(blank=True, null=True)),
                ('importe', models.FloatField(blank=True, null=True)),
                ('precio_venta', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'EspecificacionRecetas',
                'verbose_name': 'EspecificacionReceta',
                'permissions': (('list_especificacionreceta', 'Can list especificacionreceta'), ('get_especificacionreceta', 'Can get especificacionreceta')),
            },
        ),
        migrations.CreateModel(
            name='Funcionvital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuenciacardiaca', models.CharField(max_length=3)),
                ('frecuenciarespiratoria', models.FloatField()),
                ('imc', models.CharField(max_length=60)),
                ('masacorporal', models.FloatField()),
                ('peso', models.FloatField()),
                ('presionarterial', models.FloatField()),
                ('talla', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Funcionvitals',
                'verbose_name': 'Funcionvital',
                'permissions': (('list_funcionvital', 'Can list funcionvital'), ('get_funcionvital', 'Can get funcionvital')),
            },
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('atencion', models.BooleanField(default=True)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('antecedentemedico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topico2.Antecedentemedico')),
            ],
            options={
                'verbose_name_plural': 'Historias',
                'verbose_name': 'Historia',
                'permissions': (('list_historia', 'Can list historia'), ('get_historia', 'Can get historia')),
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('preciocompra', models.FloatField()),
                ('stock', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('PASTILLA', 'pastilla'), ('INYECTABLE', 'inyectable'), ('JARABE', 'jarabe'), ('VITAMINA', 'vitamina'), ('OTRO', 'otro')], default='PASTILLA', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Medicamentos',
                'verbose_name': 'Medicamento',
                'permissions': (('list_medicamento', 'Can list medicamento'), ('get_medicamento', 'Can get medicamento')),
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topico2.Departamento')),
                ('jerarquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auths.Hierarchy')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auths.Person')),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
                'verbose_name': 'Paciente',
                'permissions': (('list_paciente', 'Can list paciente'), ('get_paciente', 'Can get paciente')),
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('periododescanso', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('citafecha', models.DateTimeField(blank=True, null=True)),
                ('aministracion', models.BooleanField(default=True)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='topico2.Consulta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tratamientos',
                'verbose_name': 'Tratamiento',
                'permissions': (('list_tratamiento', 'Can list tratamiento'), ('get_tratamiento', 'Can get tratamiento')),
            },
        ),
        migrations.AddField(
            model_name='historia',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='topico2.Paciente'),
        ),
        migrations.AddField(
            model_name='historia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='especificacionreceta',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topico2.Medicamento'),
        ),
        migrations.AddField(
            model_name='especificacionreceta',
            name='tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topico2.Tratamiento'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='diagnostico',
            field=models.ManyToManyField(blank=True, to='topico2.Diagnostico'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='funcionvital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topico2.Funcionvital'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='historia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topico2.Historia'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
